# Generated by Django 6.1 on 2026-08-18 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(default='info', max_length=16)),
                ('source', models.CharField(default='app', max_length=64)),
                ('message', models.TextField()),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('value', models.TextField(blank=True, default='')),
                ('is_secret', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollectorSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('status', models.CharField(default='idle', max_length=24)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('message_count', models.BigIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='PolyMarketWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('condition_id', models.CharField(blank=True, default='', max_length=128)),
                ('question', models.TextField(blank=True, default='')),
                ('token_up', models.CharField(blank=True, default='', max_length=96)),
                ('token_down', models.CharField(blank=True, default='', max_length=96)),
                ('start_ts', models.BigIntegerField()),
                ('end_ts', models.BigIntegerField()),
                ('yes_bid', models.FloatField(blank=True, null=True)),
                ('yes_ask', models.FloatField(blank=True, null=True)),
                ('no_bid', models.FloatField(blank=True, null=True)),
                ('no_ask', models.FloatField(blank=True, null=True)),
                ('last_trade_yes', models.FloatField(blank=True, null=True)),
                ('btc_open', models.FloatField(blank=True, null=True)),
                ('btc_last', models.FloatField(blank=True, null=True)),
                ('resolved_up', models.BooleanField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('running', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=16)),
                ('config', models.JSONField(default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.BigIntegerField()),
                ('interval_seconds', models.PositiveSmallIntegerField(default=5)),
                ('mid_price', models.FloatField(blank=True, null=True)),
                ('features', models.JSONField(default=dict)),
                ('label_up_15m', models.BooleanField(blank=True, null=True)),
                ('label_poly_up', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['interval_seconds', 'ts'], name='pipeline_fe_interva_2bebdc_idx'), models.Index(fields=['label_up_15m'], name='pipeline_fe_label_u_b153bc_idx')],
                'unique_together': {('ts', 'interval_seconds')},
            },
        ),
        migrations.CreateModel(
            name='LiveTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_ms', models.BigIntegerField(db_index=True)),
                ('venue', models.CharField(db_index=True, max_length=32)),
                ('kind', models.CharField(default='trade', max_length=24)),
                ('price', models.FloatField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('is_buyer_maker', models.BooleanField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['venue', 'ts_ms'], name='pipeline_li_venue_eabcad_idx')],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.BigIntegerField(db_index=True)),
                ('market_slug', models.CharField(blank=True, default='', max_length=128)),
                ('p_up', models.FloatField()),
                ('per_model', models.JSONField(default=dict)),
                ('implied_yes', models.FloatField(blank=True, null=True)),
                ('edge', models.FloatField(blank=True, null=True)),
                ('action', models.CharField(default='hold', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.featurebar')),
            ],
        ),
        migrations.CreateModel(
            name='TradeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dry_run', models.BooleanField(default=True)),
                ('market_slug', models.CharField(max_length=128)),
                ('token_id', models.CharField(blank=True, default='', max_length=96)),
                ('outcome', models.CharField(max_length=8)),
                ('side', models.CharField(default='BUY', max_length=8)),
                ('price', models.FloatField()),
                ('size', models.FloatField()),
                ('status', models.CharField(default='created', max_length=24)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.prediction')),
            ],
        ),
        migrations.CreateModel(
            name='EnsembleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='auc_weighted', max_length=32)),
                ('min_auc', models.FloatField(default=0.52)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.trainingjob')),
            ],
        ),
        migrations.CreateModel(
            name='ModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('family', models.CharField(default='sklearn', max_length=32)),
                ('path', models.CharField(max_length=512)),
                ('metrics', models.JSONField(default=dict)),
                ('selected', models.BooleanField(default=False)),
                ('weight', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='pipeline.trainingjob')),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'created_at'], name='pipeline_mo_name_b92c16_idx')],
            },
        ),
    ]
