# Generated by Django 6.1 on 2026-08-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='featurebar',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='featurebar',
            name='asset',
            field=models.CharField(db_index=True, default='BTC', max_length=16),
        ),
        migrations.AddField(
            model_name='featurebar',
            name='label_up_next',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livetick',
            name='asset',
            field=models.CharField(db_index=True, default='BTC', max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='featurebar',
            unique_together={('asset', 'ts', 'interval_seconds')},
        ),
        migrations.AddIndex(
            model_name='featurebar',
            index=models.Index(fields=['asset', 'interval_seconds', 'ts'], name='pipeline_fe_asset_cd22c4_idx'),
        ),
        migrations.AddIndex(
            model_name='featurebar',
            index=models.Index(fields=['label_up_next'], name='pipeline_fe_label_u_57fa43_idx'),
        ),
        migrations.AddIndex(
            model_name='livetick',
            index=models.Index(fields=['asset', 'ts_ms'], name='pipeline_li_asset_41bd41_idx'),
        ),
    ]
